theme: jekyll-theme-minimal
title: SETM
timezone: America/Argentina/Buenos_Aires
permalink: /blog/:year/:title/
email: rodrigovalla@yahoo.com.ar
description: >- # this means to ignore newlines until "baseurl:"
  Simple Epidemic Transmision Models. Simple models coded in python to
  simulate the spread of some model desease.
twitter_username: rvallafoto
github_username:  rvalla
logo: /assets/img/RepoCard.jpg
show_downloads: false
plugins:
  - jekyll-feed