theme: jekyll-theme-minimal
title: SETM
timezone: America/Argentina/Buenos_Aires
permalink: /SETM/blog/:year/:title/
email: rodrigovalla@protonmail.ch
description: >- # this means to ignore newlines until "baseurl:"
  <b>S</b>imple <b>E</b>pidemic <b>T</b>ransmision <b>M</b>odels<br>
  In <a href="https://rvalla.github.io/SETM/index">english</a> - En 
  <a href="https://rvalla.github.io/SETM/index_es">español</a>
twitter_username: rvallafoto
github_username:  rvalla
logo: /assets/img/logo.jpg
show_downloads: false