theme: jekyll-theme-minimal
title: SETM
timezone: America/Argentina/Buenos_Aires
permalink: /blog/:year/:title/
email: rodrigovalla@protonmail.ch
description: >- # this means to ignore newlines until "baseurl:"
  <b>S</b>imple <b>E</b>pidemic <b>T</b>ransmision <b>M</b>odels. Simple models coded in python to
  simulate the spread of some model desease.
twitter_username: rvallafoto
github_username:  rvalla
logo: /assets/img/RepoCard.jpg
show_downloads: false